# h2proxy's config file
server {
    listen  8081 http2;     # Port that tritom_connector pushes data requests to, see docker-compose.yml
    http2   off;            # Forward messages to web_server in HTTP/1
    location /webhook {
        proxy_pass  http://127.0.0.1:8000/incoming-message;  # Port that web_server listens to (by default 8000)
    }
}
